# Models Configuration for Respondent Modelling Pipeline

random_forest:
  default:
    n_estimators: 200
    max_depth: null
    max_features: null
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
  
  gridsearch:
    enabled: True # Make sure this is on to run the grid search otherwise will use default paramms.
    param_grid:
      n_estimators: [100 ,200, 300]
      max_depth: [10 ,20]
      max_features: [0.3, 0.4, 0.5]

cross_validation:
  n_splits: 5
  user_id_var: "respondentPk"

vif_analysis:
  threshold_high: 10.0
  threshold_moderate: 5.0

target:
  outcome_var: "wonky_study_count"

shap:
  sample_size: 250
  interaction_sample_size: 125
  max_display: 25

output:
  results_file: "feature_importance_results.csv"