# Wonky Studies Configuration

# List of wonky study UUIDs
wonky_study_uuids_updated:
  "d68829df-579a-4560-b303-a7438660f421": false
  "ea2c73f9-a11a-4f52-a48c-6276544659c8": false
  "ef945e3c-f144-4048-bddc-925fb0989dfc": false
  "f3e4ccc6-d503-4ab4-82d1-9baff3ea538d": true
  "f1cffb37-ad0f-402a-9f8e-7498f9bea2bf": true
  "ffbda696-9120-4e97-9f0d-8dc2a822359e": true
  "c1ac9523-9e38-4266-92b4-fb385abeccf8": false
  "d6cd63bc-82e6-439b-b2ef-5ab002be70f1": false
  "ef8aaefb-801d-4f61-a34c-7da4340de818": false
  "eb545869-5900-4662-b116-af8a9944ee2c": false
  "f218e979-ed7c-402b-b89e-3e4ffc0d6eed": false
  "cac701cc-e5ea-4e14-999c-e499928f878a": true
  "ce79cbcb-660b-43a9-8637-990298879347": false
  "d9fd1850-6b4c-4344-8eb7-980a2e1a6b63": false
  "dc9bfa88-aa4e-4887-be00-8e4b3d4d5726": true
  "e3cf1ebe-ea58-4f3d-a856-d68c7a19ddb5": true
  "ec406c83-1df3-4ebc-8d05-c726f5b75d30": false
  "f5f3e63b-69f9-47e9-80ba-2ebff23d616d": false
  "f7422d22-b25d-4a1b-9a20-b7bf614ef303": false
  "c6a4d5cd-db4c-4bb0-b679-af05b4ee37fc": false
  "cdba5b71-fdd3-438e-9219-052ceb323986": true
  "e42caae5-1b62-4983-ab49-d3c17b30ff7f": true
  "e88b2f03-4f00-4fbc-8aa6-5f9ea20cd1f6": false
  "e5473a0d-4548-48a6-9408-7576149d7290": false
  "f47ce6f1-9acf-419a-95c2-49c75a63b357": false
  "d782681c-c976-428e-9795-6d378887601b": false
  "c92da0be-d503-42bb-9ac2-5e0a8233a688": false
  "ff6252f6-baab-413c-91b2-f7f2b0b181fd": false
  "5283cd19-88e5-43c3-a53d-08bf9cd730e0": false
  "536ff793-4fc1-4824-a047-af6dbf716fff": true
  "591eeff9-c0ae-48da-8f49-13323bba00fb": false
  "63d731ae-c9c8-41e6-9a1a-9cec9d8a757c": false
  "6a3206dd-a70a-48ca-bc66-2be8fdb58516": false
  "75c4046a-2fd6-4bef-862f-17659cc48bf5": true
  "760b91b2-a001-4e7a-9e3b-2cddc1e6e8cf": false
  "7912738e-1fbb-4a10-913f-c9a4ab295fa8": false
  "81cb0408-20c0-421e-8e4f-72af7b22c4e7": false
  "8246f75e-ec38-4981-b006-fd6b05cf3f5e": true
  "828e84e7-5b0d-47dc-86d3-22d45d8a6daf": true
  "82a87328-2b3c-4934-a46c-f8b6666d3ab3": false
  "5290c135-c6cb-4e0d-ab1e-1b29aa293de9": true
  "53d32bd9-5e18-48ae-aa1a-d3475d7fc066": false
  "8458f3a6-2aed-4516-8c9d-1adadc9a0547": true
  "529f4761-a7bf-4171-9282-1e9f8ef4879b": false
  "7a6a07fd-1a4e-4c9e-b13a-d2468f038203": true
  "7ddb40ca-3314-4249-b798-65c2da0d5957": true
  "88daec7d-4a5e-4629-be52-8658eba629eb": true
  "84e4edf3-e352-4da0-a896-c284fa99e3d1": false
  "80bdd5e3-4243-464b-86bc-89c0d4fc7ee5": false
  "81a68a08-9e0a-4287-b3bf-ae2a4a23af46": true
  "85d736af-e9b4-4d91-8e99-e7b2616e8386": false
  "5f25d2f0-ab54-4411-8fdb-b6446ca2cb5e": false
  "6859295f-6e2e-4ad7-be7c-c370091ffbfc": true
  "8a918182-9da2-4272-b51e-57b9ca8f5253": true
  "94efe5d1-f6b4-4a1c-8c63-50edb68e4718": false
  "960337ba-115d-45c2-a350-6c038ee92ea5": false
  "98dde96a-8e1f-48ad-a2ef-843229b32243": true
  "9a40b9ec-49c7-488c-9402-b8f89abfeac4": false
  "9d715e7e-3209-432d-9e4d-2ea13056948d": false
  "a5b33dcd-8206-4e43-8cac-9330818c9c47": true
  "a5bc20ef-5628-475b-b161-350cfe0a3620": true
  "af9b0591-14c3-4958-af37-36dd350b4ff4": true
  "b095c24b-6b0b-4324-a1e2-e2af15386aaa": false
  "b6252caf-95ce-405b-bf83-3f58712ccade": true
  "b7ea9037-2f59-4222-9d1d-87f0e2e8050c": true
  "953df76d-33fc-462e-9e12-552d853a4c7f": false
  "968c6a1a-a101-49ba-be79-b6c9674cdb05": true
  "a632c293-d6f6-472a-9d5e-cd85f8dac793": true
  "a6d2232c-5507-4646-a31f-c15e08d6dde0": false
  "b520dd37-d2ba-4e26-bff7-592af2dae30f": true
  "8a69bc03-0796-41a9-a0fe-85ffe74ed81a": false
  "92f34934-0f1d-42e3-bb71-75f9f5719031": false
  "99a6f654-d253-411c-8b3d-22adb15bf703": false
  "aa162339-8834-440a-ae14-39ba9d523cc4": true
  "994dc8b4-e9b7-4cb5-a797-f09bcfecd419": true
  "b90d3049-cd86-4135-ae5b-41415b45ddd4": false
  "bd8e1f46-8fd4-4569-8cab-82892fb3724f": false
  "b0f270dd-7a23-402d-a9b7-93a3136fb8a3": false
  "3411540f-beee-4832-9d97-6542f0a5db66": true
  "369c0a5f-daef-42d4-b15d-7ef1306a84a9": false
  "42710574-12eb-422a-a1ad-1053ae953dbe": false
  "507e06c5-68d4-465e-8694-9a600f158a8f": false
  "36089f7b-6c05-4110-a8e6-5cb53e8fb3f9": true
  "3bb02fff-344c-44f4-a947-8b842fdb2273": false
  "3e18da08-f8a2-4793-8011-22b2fe4437da": false
  "3fba2a28-b7c9-468d-a257-cfda7100a25f": true
  "40dceecb-5f46-4c1b-a830-0c2d9c78f54d": false
  "43d23d27-06ca-4fa8-b6c3-d42d422e459a": true
  "49f2e76e-779e-40bb-90fa-953492938a50": true
  "51f369c2-3130-4809-a0f6-c4a9006c7c3a": true
  "2e4febfb-e789-4aba-8715-f6e0480ef50a": false
  "312d09bf-0633-431c-837e-df00c6e9ffad": false
  "35bdadcb-f85b-4b3a-b92f-4d498fa7e1d9": false
  "435e1364-682d-48a4-b79b-e9608cdfdd00": true

# Columns to include from balance tables
cols_to_include_subset:
  - "respondent_pk"
  - "survey_pk"
  - "platform_name"
  - "hardware_version"
  - "yob"
  - "survey_locale"
  - "request-remote-addr"
  - "user-agent"
  - "exposure_band"
  - "survey_type"

# Columns to group by for aggregation
cols_to_group:
  - "respondent_pk"
  - "survey_pk"
  - "platform_name"
  - "hardware_version"
  - "yob"
  - "survey_locale"
  - "request-remote-addr"
  - "user-agent"
  - "exposure_band"
  - "survey_type"
  - "task_pk"
  - "task_origin_id"
  - "task_length_of_task"
  - "task_country"
  - "task_targeting_type"
  - "task_category"
  - "task_points"
  - "activation_date"

# Columns to exclude from respondent_info table (reduces memory footprint)
cols_to_exclude_respondent_info:
  - "alcoholFrequency"
  - "alcohol_frequency"
  - "all_starts_last_30_days"
  - "auto_car_brand"
  - "auto_car_brand_mc"
  - "auto_car_future_purchase"
  - "auto_car_manufacture_date"
  - "auto_car_purchase_date"
  - "auto_car_purchase_type"
  - "auto_car_type"
  - "auto_car_type_mc"
  - "auto_decision_maker"
  - "auto_motorcycle_use"
  - "beverageRegularConsumption"
  - "beverage_regular_consumption_mc"
  - "beverage_p4w"
  - "beverage_p4w_mc"
  - "cellular_plan"
  - "children_age_and_gender"
  - "children_age_and_gender_mc"
  - "children_gender"
  - "children_in_household"
  - "children_number_in_household"
  - "children_yob"
  - "clothing_and_homeware_retailer"
  - "clothing_and_homeware_retailer_main"
  - "clothing_purchase"
  - "clothing_purchase_frequency"
  - "clothing_retailer_denim"
  - "clothing_retailer_denim_main"
  - "consumer_traits"
  - "ethnicity_hispanic"
  - "exercise_hours"
  - "exercise_hours_mc"
  - "eyewear"
  - "fastfood_frequency"
  - "fastfood_frequency"
  - "flight_destination"
  - "flight_destination_mc"
  - "flight_purpose"
  - "flight_use"
  - "grocery_shopper"
  - "hobbies"
  - "hobbies_mc"
  - "holiday_accommodation"
  - "home_improvement_category"
  - "home_improvement_retailers_kitchen"
  - "homeware_retailer"
  - "hotel_use"
  - "household_investable_assets"
  - "household_other_industry"
  - "household_other_industry_mc"
  - "household_pets"
  - "household_pets_mc"
  - "level_of_education"
  - "main_grocery_shop"
  - "malaysian_ethnicity"
  - "region"
  - "regionOther1"
  - "region_city_state"
  - "region_level1"
  - "region_level2"
  - "region_level3"
  - "region_nuts1"

# Columns to drop
cols_to_drop:
  - "id"
  - "version"
  - "amount"
  - "button_text"
  - "category"
  - "description"
  - "epc"
  - "field_end_date"
  - "expiry_date"
  - "for_android"
  - "for_ios"
  - "last_updated"
  - "link"
  - "origin"
  - "points"
  - "public_description"
  - "public_logo"
  - "public_title"
  - "ratio"
  - "status"
  - "last_task_query_id"
  - "title"
  - "workflow_description"
  - "rank"
  - "language"
  - "group_pk"
  - "reference_url"
  - "field_begin_date"
  - "additional"
  - "auto_deactivate"
  - "sequence_id"
  - "sequence_index"
  - "exchange_rate"
  - "margin"
  - "number_of_time_activated"
  - "workflow_type"
  - "Op"
  - "additional_map"
  - "buyer"
  - "unrepresented_quals"
  - "unrepresented_quota"
